on:
  schedule:
    - cron: "0 */3 * * *" # every 3rd hour
name: Pull Data and Build
jobs:
  build:
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install npm modules
        run: npm install
      - name: Build
        run: npm run build
      - name: Scrape website
        run: npm run scrape
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated build and scrape
          branch: main
